mongo:
  image: mongo
  restart: always
  volumes:
    - database:/data/db
  ports:
    - "27017:27017"

rabbitmq:
  container_name: reduceurl_rabbitmq_1
  image: rabbitmq:3-management
  ports:
    - 5672:5672
    - 15672:15672
  command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server"
  volumes:
    - ./docker/queue/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    - ./docker/queue/definitions.json:/etc/rabbitmq/definitions.json:ro


app:
  build:  .
  dockerfile: docker/Dockerfile
  ports:
    - "8080:8080"
  links:
    - mongo
